#!/bin/sh

source Pkgfile
source /etc/pkgmk.conf

[ -z "$PKGMK_WORK_DIR" ] && PKGMK_WORK_DIR="$PWD/work"
[ -z "$PKGMK_SOURCE_DIR" ] && PKGMK_SOURCE_DIR="$PWD"

if [ -e "$PKGMK_SOURCE_DIR/$sname-$version.tar.lzma" ]; then
	echo 'You have the latist source file.'
	exit
fi

if [ -n "`pkginfo -i | egrep '^xdelta '`" ]; then
	if [ -e "$PKGMK_SOURCE_DIR/$sname-$OLD_VERSION.tar.lzma" ]; then

		if [ ! -e "$PKGMK_WORK_DIR" ]; then
			mkdir -p "$PKGMK_WORK_DIR"
		fi
		cd "$PKGMK_WORK_DIR"

		if [ ! -e "$PKGMK_SOURCE_DIR/$sname-$OLD_VERSION.tar-$sname-$version.tar.xdelta" ]; then
			wget http://www.dcaf-security.org/distfiles/$sname-$OLD_VERSION.tar-$sname-$version.tar.xdelta --directory-prefix=$PKGMK_SOURCE_DIR
		fi

		cp $PKGMK_SOURCE_DIR/$sname-$OLD_VERSION.tar.lzma .
		cp $PKGMK_SOURCE_DIR/$sname-$OLD_VERSION.tar-$sname-$version.tar.xdelta .
		echo -n '[ 33%] Decompressing source, '
		lzma -d $sname-$OLD_VERSION.tar.lzma
		echo 'done.'
		echo -n '[ 66%] Patching source, '
		xdelta patch $sname-$OLD_VERSION.tar-$sname-$version.tar.xdelta
		rm $sname-$OLD_VERSION.tar
		mv $sname-$OLD_VERSION.tar-$sname-$version.tar.xdelta $PKGMK_SOURCE_DIR/
		echo 'done.'
		echo -n '[100%] Compressing patched source, '
		lzma -9 $sname-$version.tar
		echo 'done.'
		mv $sname-$version.tar.lzma $PKGMK_SOURCE_DIR/
	else
		echo "'$sname-$OLD_VERSION.tar.lzma' not found proceed to run Pkgfile."
		exit
	fi
else
	echo "Warning: 'xdelta' is not installed can not do a incremental update."
fi

# End of file
