#!/bin/bash
#
# Copyright (c) 2012 by Matt Housh, jaeger at morpheus dot net
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PORTS32="`prt-get listinst | grep -- -32$`"

for P in $PORTS32
do
	if [ "`prt-get info $P 2>&1`" != "Package '$P' not found" ]
	then
		PORT="`echo $P | sed 's/-32$//'`"
		. $(prt-get path $PORT)/Pkgfile
		PV=$version
		. $(prt-get path $P)/Pkgfile
		PV32=$version
		if [ "$PV" != "$PV32" ]
		then
			echo "$P $PV32 - $PORT $PV"
		fi
	fi
done
