#!/usr/bin/perl -w

use strict;

my $SLASH_SEP  = q{/};

sub dirWalkRec {
  my ($top, $filefunc_ref, $dirfunc_ref) = @_;
  my $DIR;

  if (-d $top) 
  {
      unless (opendir $DIR, $top) {
          return; 
      }

      my $file;
      my @results;

      while ($file = readdir $DIR) {
          
          next if $file eq '.' || $file eq '..';
          
          push @results, 

          dirWalkRec($top . $SLASH_SEP . $file, $filefunc_ref, $dirfunc_ref);
      }

      return $dirfunc_ref ? $dirfunc_ref->($top, @results) : () ;

  } 
  else 
  {
      return $filefunc_ref ? $filefunc_ref->($top): () ;
  }
}

$ARGV[0] ||= '.';
$ARGV[0] =~ s!/*$!!o;

# remove junk and temp files
# &dirWalkRec( $ARGV[0], sub {unlink $_[0] if ($_[0] =~ m!\~$!);} );
&dirWalkRec( $ARGV[0], sub {print "$_[0]\n" if -f $_[0];} );
exit 0;
