#!/bin/bash
#
# Copyright (c) 2008 by Jose V Beneyto, sepen at users dot sourceforge dot net
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

msgUsage() {
  echo "Usage: $APPNAME <options> [path1, path2, ...]"
  echo "Where options are:"
  echo "  -h        Show this help information"
  echo "  -wl file  Use whitelist file"
  echo "Read $APPNAME(1) for more info"
  exit 0
}

msgError() {
  echo "Error, $@" 2>&1
  exit 1
}

findPathNot() {
  for path in $@; do
    [ ! -d "$path" ] && msgError "can't open directory '$path'"
    path="$(cd $path; pwd)"
    find ${path} | sed 's|^/||' | while read p; do
      p="$(echo "${p}" | sed 's|]$|\\]|')"
      if [ ! "$(grep "${p}" $PKGDB 2>/dev/null)" ]; then
        if [ -e "$WLFILE" -o -L "$WLFILE" ]; then
          [ ! "$(grep "${p}" $WLFILE 2>/dev/null)" ] && echo "/${p}"
        else
          echo "/${p}"
        fi
      fi
    done 
  done
}

main() {
  case $1 in
    -wl) 
      [ ! -r "$2" ] && msgErorr "can't read whitelist file '$2'"
      WLFILE="$2"
      shift 2
      findPathNot $@
      ;;
    -*)
      msgUsage
      ;;
    *)
      findPathNot $@
      ;;
  esac
} 

APPNAME="$(basename $0)"
PKGDB="/var/lib/pkg/db"
WLFILE=""

[ ! -r "$PKGDB" ] && msgError "can't open pkg database '$PKGDB'"
[ $# -lt 1 ] && msgUsage

main $@

# End of File
